services:
  frivas-web:
    build:
      context: .
    container_name: frivas-web
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - sotter-network
    labels:
      - traefik.enable=true

      # Servicio interno Next.js
      - traefik.http.services.frivas.loadbalancer.server.port=3000

      # HTTPS router
      - traefik.http.routers.frivas.rule=Host(`frivassteel.ca`) || Host(`www.frivassteel.ca`)
      - traefik.http.routers.frivas.entrypoints=websecure
      - traefik.http.routers.frivas.tls=true
      - traefik.http.routers.frivas.tls.certresolver=letsencrypt
      - traefik.http.routers.frivas.middlewares=frivas-wwwredirect

      # HTTP router
      - traefik.http.routers.frivas-http.rule=Host(`frivassteel.ca`) || Host(`www.frivassteel.ca`)
      - traefik.http.routers.frivas-http.entrypoints=web
      - traefik.http.routers.frivas-http.middlewares=frivas-https-redirect

      # HTTP -> HTTPS
      - traefik.http.middlewares.frivas-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.frivas-https-redirect.redirectscheme.permanent=true

      # www -> root
      - traefik.http.middlewares.frivas-wwwredirect.redirectregex.regex=^https://www\.frivassteel\.ca/(.*)
      - traefik.http.middlewares.frivas-wwwredirect.redirectregex.replacement=https://frivassteel.ca/$${1}
      - traefik.http.middlewares.frivas-wwwredirect.redirectregex.permanent=true

networks:
  sotter-network:
    external: true